// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uexaanitbyryefpzzleo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVleGFhbml0YnlyeWVmcHp6bGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzI4MDgsImV4cCI6MjA2NTgwODgwOH0.lpua86Z9OKstI0DTH8gxr2KTdCmVsL3gDvz-ysnqgN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);